export const mockCategories = [
  {
    id: "cat-ai-models",
    name: "AI Models",
    nameAr: "نماذج الذكاء الاصطناعي",
    slug: "ai-models",
  },
  {
    id: "cat-research",
    name: "Research",
    nameAr: "البحوث",
    slug: "research",
  },
  {
    id: "cat-companies",
    name: "Companies",
    nameAr: "الشركات",
    slug: "companies",
  },
] as const;

export const mockArticles = [
  {
    id: "article-openai-gpt5",
    title: "OpenAI announces GPT-5",
    titleAr: "OpenAI تعلن عن GPT-5",
    slug: "openai-announces-gpt-5",
    content: "OpenAI has announced GPT-5, the latest version of their language model...",
    contentAr:
      "أعلنت OpenAI عن GPT-5، أحدث إصدار من نموذج اللغة الخاص بهم... يتميز النموذج الجديد بقدرات محسنة في الفهم والتوليد، مع دعم أفضل للغات المتعددة بما في ذلك العربية.",
    excerpt: "أعلنت OpenAI عن GPT-5 بقدرات محسنة",
    imageUrl: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800",
    sourceUrl: "https://techcrunch.com/sample",
    sourceName: "TechCrunch",
    score: 9,
    published: true,
    publishedAt: new Date(),
    categoryId: "cat-ai-models",
    category: mockCategories[0],
  },
  {
    id: "article-deepmind-protein",
    title: "Google DeepMind breakthrough in protein folding",
    titleAr: "اختراق Google DeepMind في طي البروتين",
    slug: "google-deepmind-protein-folding",
    content: "Google DeepMind has achieved a major breakthrough...",
    contentAr: "حققت Google DeepMind اختراقاً كبيراً في مجال طي البروتين باستخدام الذكاء الاصطناعي...",
    excerpt: "اختراق جديد في علم البروتين",
    imageUrl: "https://images.unsplash.com/photo-1576086213369-97a306d36557?w=800",
    sourceUrl: "https://venturebeat.com/sample",
    sourceName: "VentureBeat",
    score: 8,
    published: true,
    publishedAt: new Date(Date.now() - 86400000),
    categoryId: "cat-research",
    category: mockCategories[1],
  },
  {
    id: "article-microsoft-ai",
    title: "Microsoft invests $10B in AI infrastructure",
    titleAr: "Microsoft تستثمر 10 مليار دولار في البنية التحتية للذكاء الاصطناعي",
    slug: "microsoft-ai-investment",
    content: "Microsoft announces massive investment...",
    contentAr: "أعلنت Microsoft عن استثمار ضخم بقيمة 10 مليار دولار...",
    excerpt: "استثمار ضخم من Microsoft",
    imageUrl: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800",
    sourceUrl: "https://techcrunch.com/sample",
    sourceName: "TechCrunch",
    score: 8,
    published: true,
    publishedAt: new Date(Date.now() - 172800000),
    categoryId: "cat-companies",
    category: mockCategories[2],
  },
] as const;
