-- Distribution Engine — Sprint 4
-- Additive only: creates two new tables (DistributionTarget, DistributionTask).
-- Does not alter, rename, or drop any existing table, column, or constraint.
-- Hand-written (not generated by `prisma migrate dev`) because this database
-- has pre-existing, unrelated migration-history drift — see
-- docs/distribution-engine-sprint4.md's "Migration Status" section for the
-- full explanation and why `prisma migrate dev` was not used to produce this
-- file. Review before applying; this file was never run against any database.

-- CreateTable
CREATE TABLE "public"."DistributionTarget" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "targetType" TEXT NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT false,
    "config" TEXT NOT NULL,
    "credentials" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "DistributionTarget_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."DistributionTask" (
    "id" TEXT NOT NULL,
    "targetId" TEXT NOT NULL,
    "contentType" TEXT NOT NULL,
    "contentId" TEXT NOT NULL,
    "idempotencyKey" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "attemptCount" INTEGER NOT NULL DEFAULT 0,
    "nextAttemptAt" TIMESTAMP(3),
    "sendingAt" TIMESTAMP(3),
    "lastAttemptAt" TIMESTAMP(3),
    "sentAt" TIMESTAMP(3),
    "externalId" TEXT,
    "externalUrl" TEXT,
    "errorMsg" TEXT,
    "payloadSnapshot" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "DistributionTask_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "DistributionTarget_targetType_enabled_idx" ON "public"."DistributionTarget"("targetType", "enabled");

-- CreateIndex
CREATE UNIQUE INDEX "DistributionTask_idempotencyKey_key" ON "public"."DistributionTask"("idempotencyKey");

-- CreateIndex
CREATE INDEX "DistributionTask_status_nextAttemptAt_idx" ON "public"."DistributionTask"("status", "nextAttemptAt");

-- CreateIndex
CREATE INDEX "DistributionTask_targetId_idx" ON "public"."DistributionTask"("targetId");

-- CreateIndex
CREATE INDEX "DistributionTask_contentType_contentId_idx" ON "public"."DistributionTask"("contentType", "contentId");

-- AddForeignKey
ALTER TABLE "public"."DistributionTask" ADD CONSTRAINT "DistributionTask_targetId_fkey" FOREIGN KEY ("targetId") REFERENCES "public"."DistributionTarget"("id") ON DELETE CASCADE ON UPDATE CASCADE;
